const mockCommentData = [
  {
    id: '1',
    author: 'John Doe',
    text: 'This is a great video, I really enjoyed it!',
    date: '2023-12-06T10:15:00Z',
    likeCount: 25,
    sentimentScore: 0.8,
  },
  {
    id: '2',
    author: 'Jane Smith',
    text: 'I disagree with the points made in this video.',
    date: '2023-12-05T14:30:00Z',
    likeCount: 10,
    sentimentScore: -0.4,
  },
  {
    id: '3',
    author: 'Mike Johnson',
    text: 'Interesting insights, but could use more examples.',
    date: '2023-12-05T09:00:00Z',
    likeCount: 15,
    sentimentScore: 0.5,
  },
  {
    id: '4',
    author: 'Emily Davis',
    text: 'Loved it! Very informative and well-presented.',
    date: '2023-12-04T12:45:00Z',
    likeCount: 40,
    sentimentScore: 0.9,
  },
  {
    id: '1',
    author: 'John Doe',
    text: 'This is a great video, I really enjoyed it!',
    date: '2023-12-06T10:15:00Z',
    likeCount: 25,
    sentimentScore: 0.8,
  },
  {
    id: '2',
    author: 'Jane Smith',
    text: 'I disagree with the points made in this video.',
    date: '2023-12-05T14:30:00Z',
    likeCount: 10,
    sentimentScore: -0.4,
  },
  {
    id: '3',
    author: 'Mike Johnson',
    text: 'Interesting insights, but could use more examples.',
    date: '2023-12-05T09:00:00Z',
    likeCount: 15,
    sentimentScore: 0.5,
  },
  {
    id: '4',
    author: 'Emily Davis',
    text: 'Loved it! Very informative and well-presented.',
    date: '2023-12-04T12:45:00Z',
    likeCount: 40,
    sentimentScore: 0.9,
  },
  {
    id: '1',
    author: 'John Doe',
    text: 'This is a great video, I really enjoyed it!',
    date: '2023-12-06T10:15:00Z',
    likeCount: 25,
    sentimentScore: 0.8,
  },
  {
    id: '2',
    author: 'Jane Smith',
    text: 'I disagree with the points made in this video.',
    date: '2023-12-05T14:30:00Z',
    likeCount: 10,
    sentimentScore: -0.4,
  },
  {
    id: '3',
    author: 'Mike Johnson',
    text: 'Interesting insights, but could use more examples.',
    date: '2023-12-05T09:00:00Z',
    likeCount: 15,
    sentimentScore: 0.5,
  },
  {
    id: '4',
    author: 'Emily Davis',
    text: 'Loved it! Very informative and well-presented.',
    date: '2023-12-04T12:45:00Z',
    likeCount: 40,
    sentimentScore: 0.9,
  },
  {
    id: '1',
    author: 'John Doe',
    text: 'This is a great video, I really enjoyed it!',
    date: '2023-12-06T10:15:00Z',
    likeCount: 25,
    sentimentScore: 0.8,
  },
  {
    id: '2',
    author: 'Jane Smith',
    text: 'I disagree with the points made in this video.',
    date: '2023-12-05T14:30:00Z',
    likeCount: 10,
    sentimentScore: -0.4,
  },
  {
    id: '3',
    author: 'Mike Johnson',
    text: 'Interesting insights, but could use more examples.',
    date: '2023-12-05T09:00:00Z',
    likeCount: 15,
    sentimentScore: 0.5,
  },
  {
    id: '4',
    author: 'Emily Davis',
    text: 'Loved it! Very informative and well-presented.',
    date: '2023-12-04T12:45:00Z',
    likeCount: 40,
    sentimentScore: 0.9,
  },
];

export default mockCommentData;
